
console.log('process?.env.NODE_ENV',process.env.NODE_ENV)
const { COMPTROLLER_MAIN, RPCURLS_MAIN, SUBGRAPH_URL_MAIN,CONTRACT_CBASE_ABI_MAIN ,C_TOKEN_NAME_MAIN,CONTRACT_COMPTROLLER_ABI_MAIN} = require('./address-main')
const { COMPTROLLER_TEST, RPCURLS_TEST, SUBGRAPH_URL_TEST, CONTRACT_CBASE_ABI_TEST,CONTRACT_CBEP_ABI_TEST, C_TOKEN_NAME_TEST,CONTRACT_COMPTROLLER_ABI_TEST } = require('./address-test')

const SUBGRAPH_URL = 
process.env.NODE_ENV === 'prod'? SUBGRAPH_URL_MAIN : SUBGRAPH_URL_TEST

const COMPTROLLER = 
process.env.NODE_ENV === 'prod'? COMPTROLLER_MAIN : COMPTROLLER_TEST

const RPCURLS = 
process.env.NODE_ENV === 'prod'? RPCURLS_MAIN : RPCURLS_TEST

const CONTRACT_CBASE_ABI =
process.env.NODE_ENV === 'prod'? CONTRACT_CBASE_ABI_MAIN : CONTRACT_CBASE_ABI_TEST

const  CONTRACT_CBEP_ABI =
process.env.NODE_ENV === 'prod'? CONTRACT_CBASE_ABI_MAIN : CONTRACT_CBASE_ABI_TEST


const comptrollerAbi =
process.env.NODE_ENV === 'prod'? CONTRACT_COMPTROLLER_ABI_MAIN : CONTRACT_COMPTROLLER_ABI_TEST


const C_TOKEN_NAME = 
process.env.NODE_ENV === 'prod'? C_TOKEN_NAME_MAIN : C_TOKEN_NAME_TEST



module.exports = {
  SUBGRAPH_URL,
  COMPTROLLER,
  comptrollerAbi,
  RPCURLS,
  CONTRACT_CBEP_ABI,
  CONTRACT_CBASE_ABI,
  C_TOKEN_NAME
}
